CREATE DATABASE user_info;

USE user_info;

CREATE TABLE (
    id INT AUTOINCREMENT PRIMARY KEY,
    username VARCHAR(225) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);